networks:
  capstone:
    external: false

services:
  eureka:
    image: springcloud/eureka:latest
    networks:
      - capstone
    ports:
      - '8761:8761'

  gateway:
    build: ./gateway
    depends_on:
      - eureka
    environment:
      - SERVER_PORT=8080
      - EUREKA_HOST=eureka
    networks:
      - capstone
    ports:
      - '8080:8080'

  kafka:
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    image: 'bitnami/kafka:latest'    
    networks:
      - capstone
    ports:
      - '9092:9092'

  queryparser:
    build: ./queryparser
    depends_on:
      - eureka
    environment:
      - SERVER_PORT=8082
      - EUREKA_HOST=eureka
    networks:
      - capstone
    ports:
      - '8082'

  webcrawler:
    build: ./webcrawler
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - capstone

  websitepersistence:
    build: ./websitepersistence
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - NEO4J_URI=$NEO4J_URI
      - NEO4J_PASSWORD=$NEO4J_PASSWORD
    networks:
      - capstone

  websiteretrieval:
    build: ./websiteretrieval
    depends_on:
      - eureka
    environment:
      - SERVER_PORT=8081
      - EUREKA_HOST=eureka
    networks:
      - capstone
    ports:
      - '8081'
