services:
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  webcrawler:
    build: ./webcrawler
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9092
      - SERVER_PORT=8080
    ports:
      - '8080'

  websitePersistence:
    build: ./websitepersistence
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9092
      - NEO4J_URI=${NEO4J_URI}
      - NEO$J_USERNAME=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - SERVER_PORT=8081
    ports:
      - '8081'
