services:
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - '9092:9092'

  webcrawler:
    build: ./webcrawler
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_PRODUCER_BOOTSTRAPSERVERS=kafka:9092


  websitepersistence:
    build: ./websitepersistence
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_CONSUMER_BOOTSTRAPSERVERS=kafka:9092
      - SPRING_NEO4J_URI=$NEO4J_URI
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=$NEO4J_PASSWORD
