eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: 'http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/'

server:
  port: '${SERVER_PORT:8080}'

spring:
  application:
    name: SEARCH-API
