eureka:
  client:
    service-url:
      defaultZone: 'http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/'

server:
  port: '${SERVER_PORT:8080}'
  
spring:
  application:
    name: gateway-service
