server:
    port: "${SERVER_PORT:8080}"
eureka:
  client:
    service-url:
      defaultZone: "http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka"
spring:
  application:
    name: query-parser-service